[advisories]
version = 2
ignore = [
  "RUSTSEC-2024-0436",  # 忽略 paste 库不再维护的提醒
]

[licenses]
version = 2
allow = [
  "Apache-2.0",
  "MIT",
  "BSD-3-Clause",
  "Unicode-3.0",
  "ISC",
  "OpenSSL",
  "CDLA-Permissive-2.0",
  "Zlib",
  "BSD-2-Clause",
  "NCSA",
  "LicenseRef-Slint-Royalty-free-2.0",
  "MPL-2.0",
  "0BSD",
  "BSL-1.0"
]
confidence-threshold = 1.0

[bans]
# We don't maintain a fixed Cargo.lock so enforcing
# `multiple-versions = "deny"` is impractical.
multiple-versions = "allow"
wildcards = "deny"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
